export const layout = {
    canvas : {
        position: 'relative',
        height: 500,
        width: 500,
    },
    Appmain : {
        position: "absolute",
        backgroundColor: "#21295C",
        height: "100vh",
        width: "100vw",
    },
    leftSection : {
        position: "absolute",
        padding: 50,
        width: 'auto',
    },
    rightSection : {
        position: "absolute",
        left: 600,
        top: 0,
    },
    generateButton: {
        position: "absolute",
        backgroundColor: "#1C7293",
        color: "#EEF1F4",
        fontSize: 30,
        left: 55,
        top: 50,
        width: 140,
        border: 'none',
        borderBottom: '2px solid black',
        borderRight: '2px solid black',
    },
    sizeInput: {
        position: "absolute",
        color: "#EEF1F4",
        fontSize: 20,
        left: 55,
        top: 150,
        width: 140,
        border: 'none',
    },
    inputText: {
        position: "absolute",
        color: "#EEF1F4",
        backgroundColor: "#1C7293",
        fontSize: 15,
        left: 155,
        top: 155,
        width: 35,
        border: 'none',
    },
    stepButton: {
        position: "absolute",
        backgroundColor: "#1C7293",
        color: "#EEF1F4",
        fontSize: 30,
        left: 55,
        top: 100,
        width: 140,
        border: 'none',
        borderBottom: '2px solid black',
        borderRight: '2px solid black',
    },
    resetButton: {
        position: "absolute",
        backgroundColor: "#1C7293",
        color: "#EEF1F4",
        fontSize: 30,
        width: 140,
        left: 55,
        top: 250,
        border: 'none',
        borderBottom: '2px solid black',
        borderRight: '2px solid black',
    },
};