export const layout = {
    canvas : {
        position: 'relative',
        height: 500,
        width: 500,
    },
    Appmain : {
        position: "absolute",
        backgroundColor: "#21295C",
        height: "100vh",
        width: "100vw",
    },
    leftSection : {
        position: "absolute",
        //left: 50,
        //top: 50,
        padding: 50,
        //float: 'left',
        //height: "100vh",
        width: 'auto',
        //backgroundColor: "#120a37",
        //alignItems: "center",
        //justifyContent:'center',
        //flex: 1,
    },
    middleSection : {
        position: "absolute",
        //backgroundColor: "#0a3712",
        //height: "100vh",
        //width: 'auto',
        //float: 'middle',
        //left: leftSection.width
        left: 600,
        top: 0,
        //margin: 50,
        //alignItems: "center",
        //justifyContent:'center',
        //flex: 1,
    },
    rightSection: {
        position: "absolute",
        //backgroundColor: "#0000ff",
        left: 900,
        top: 50,
        //width: 300,
        //height: 300,
        //float: 'right',
    },
    movetext: {
        fontSize: 30,
        position: "absolute",
        left: 50,
        top: 125,
        color: "#EEF1F4",
        textAlign: 'center',
        width: 200,
    },
    scoretext: {
        fontSize: 30,
        position: "absolute",
        left: 50,
        top: 80,
        color: "#EEF1F4",
        textAlign: 'center',
        width: 200,
    },
    level1Button: {
        position: "absolute",
        backgroundColor: "#1C7293",
        color: "#EEF1F4",
        fontSize: 30,
        left: 55,
        top: 50,
        width: 130,
        border: 'none',
        borderBottom: '2px solid black',
        borderRight: '2px solid black',
    },
    level2Button: {
        position: "absolute",
        backgroundColor: "#1C7293",
        color: "#EEF1F4",
        fontSize: 30,
        left: 55,
        top: 100,
        width: 130,
        border: 'none',
        borderBottom: '2px solid black',
        borderRight: '2px solid black',
    },
    level3Button: {
        position: "absolute",
        backgroundColor: "#1C7293",
        color: "#EEF1F4",
        fontSize: 30,
        left: 55,
        top: 150,
        width: 130,
        border: 'none',
        borderBottom: '2px solid black',
        borderRight: '2px solid black',
    },
    resetButton: {
        position: "absolute",
        backgroundColor: "#1C7293",
        color: "#EEF1F4",
        fontSize: 30,
        width: 130,
        left: 55,
        top: 250,
        border: 'none',
        borderBottom: '2px solid black',
        borderRight: '2px solid black',
    },
    victory: {
        fontSize: 40,
        position: "absolute",
        color: "#EEF1F4",
        width: 250,
        left: 0,
        textAlign: 'center',
        top: 300,
    },
    buttons: {
        //fontSize: 30,
        position: "absolute",
        left: 30,
        top: 175,
    },
    upbutton: {
        fontSize: 30,
        position: "absolute",
        backgroundColor: "#1C7293",
        color: "#EEF1F4",
        left: 100,
        top: 30,
        width: 35,
        height: 35,
        border: 'none',
        borderBottom: '2px solid black',
        borderRight: '2px solid black',
    },
    downbutton: {
        fontSize: 30,
        position: "absolute",
        backgroundColor: "#1C7293",
        color: "#EEF1F4",
        left: 100,
        width: 35,
        height: 35,
        top: 230,
        border: 'none',
        borderBottom: '2px solid black',
        borderRight: '2px solid black',
    },
    leftbutton: {
        fontSize: 30,
        position: "absolute",
        backgroundColor: "#1C7293",
        color: "#EEF1F4",
        top: 130,
        width: 35,
        height: 35,
        border: 'none',
        borderBottom: '2px solid black',
        borderRight: '2px solid black',
    },
    rightbutton: {
        fontSize: 30,
        position: "absolute",
        backgroundColor: "#1C7293",
        color: "#EEF1F4",
        left: 200,
        width: 35,
        height: 35,
        top: 130,
        border: 'none',
        borderBottom: '2px solid black',
        borderRight: '2px solid black',
    },
};